name: automl_projects
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - adwaita-icon-theme=49.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiohttp-retry=2.9.1
  - aiosignal=1.4.0
  - amqp=5.3.1
  - annotated-types=0.7.0
  - antlr-python-runtime=4.9.3
  - anyio=4.12.1
  - appdirs=1.4.4
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.1.0
  - async-timeout=5.0.1
  - asyncssh=2.21.1
  - atk-1.0=2.38.0
  - atpublic=7.0.0
  - attrs=25.4.0
  - babel=2.17.0
  - backports.zoneinfo=0.2.1
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - billiard=4.2.4
  - blas=2.305
  - blas-devel=3.11.0
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - boto3=1.42.43
  - botocore=1.42.43
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - celery=5.4.0
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1.2
  - click-repl=0.3.0
  - colorama=0.4.6
  - comm=0.2.3
  - configobj=5.0.9
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dictdiffer=0.9.0
  - diskcache=5.6.3
  - distro=1.9.0
  - dpath=2.2.0
  - dulwich=1.0.0
  - dvc=3.66.1
  - dvc-data=3.18.2
  - dvc-gdrive=3.0.1
  - dvc-http=2.32.0
  - dvc-objects=5.2.0
  - dvc-render=1.0.2
  - dvc-studio-client=0.22.0
  - dvc-task=0.40.2
  - entrypoints=0.4
  - epoxy=1.5.10
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - filelock=3.20.3
  - flatten-dict=0.4.2
  - flufl.lock=9.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - funcy=1.18
  - future=1.0.0
  - gdk-pixbuf=2.44.5
  - gitdb=4.0.12
  - gitpython=3.1.46
  - glib-tools=2.86.3
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-api-core=2.29.0
  - google-api-python-client=2.189.0
  - google-auth=2.48.0
  - google-auth-httplib2=0.3.0
  - googleapis-common-protos=1.72.0
  - grandalf=0.7
  - graphite2=1.3.14
  - graphviz=14.1.2
  - gtk3=3.24.43
  - gto=1.9.0
  - gts=0.7.6
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=12.3.2
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - httpcore=1.0.9
  - httplib2=0.31.2
  - httpx=0.28.1
  - hydra-core=1.3.2
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - iterative-telemetry=0.0.10
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.1.0
  - joblib=1.5.3
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter-lsp=2.3.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.4
  - jupyterlab=4.5.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - kiwisolver=1.4.9
  - kombu=5.6.2
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20260107.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgd=2.3.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgit2=1.9.2
  - libglib=2.86.3
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.2
  - libopenblas=0.3.30
  - libpng=1.6.54
  - librsvg=2.60.0
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - mistune=3.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclient=0.10.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - oauth2client=4.1.3
  - omegaconf=2.3.0
  - openblas=0.3.30
  - openjpeg=2.5.4
  - openssl=3.6.1
  - orjson=3.11.5
  - overrides=7.7.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.5
  - pathlib2=2.3.7.post1
  - pathspec=0.12.1
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prometheus_client=0.24.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - proto-plus=1.27.1
  - psutil=7.2.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.6.2
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-settings=2.12.0
  - pydot=4.0.1
  - pydrive2=1.21.3
  - pygit2=1.18.2
  - pygments=2.19.2
  - pygtrie=2.5.0
  - pyobjc-core=12.1
  - pyobjc-framework-cocoa=12.1
  - pyopenssl=24.2.1
  - pyparsing=3.3.2
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.2.1
  - python-fastjsonschema=2.21.2
  - python-gssapi=1.11.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytorch=2.2.2
  - pytz=2025.2
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.3.2
  - rpds-py=0.30.0
  - rsa=4.9.1
  - ruamel.yaml=0.19.1
  - ruamel.yaml.clib=0.2.15
  - s3transfer=0.16.0
  - scikit-learn=1.7.2
  - scipy=1.11.4
  - scmrepo=3.6.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - semver=3.0.4
  - send2trash=2.1.0
  - setuptools=80.10.1
  - shellingham=1.5.4
  - shortuuid=1.0.13
  - shtab=1.8.0
  - six=1.17.0
  - smmap=5.0.2
  - sniffio=1.3.1
  - soupsieve=2.8.3
  - sqltrie=0.11.2
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - sympy=1.12.1
  - tabulate=0.9.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.1
  - tk=8.6.13
  - tomli=2.4.0
  - tomlkit=0.14.0
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.21.1
  - typer-slim=0.21.1
  - typer-slim-standard=0.21.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - uritemplate=4.2.0
  - urllib3=2.6.3
  - vine=5.1.0
  - voluptuous=0.16.0
  - wcwidth=0.4.0
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.46.3
  - widgetsnbextension=4.0.15
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yarl=1.22.0
  - zc.lockfile=4.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - accelerate==0.29.3
      - cachetools==6.2.6
      - cryptography==46.0.3
      - datasets==2.18.0
      - dill==0.3.8
      - dlib==20.0.0
      - evaluate==0.4.6
      - face-recognition==1.3.0
      - face-recognition-models==0.3.0
      - filetype==1.2.0
      - frozenlist==1.8.0
      - fsspec==2024.2.0
      - google-genai==1.60.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - imagehash==4.3.2
      - jsonpatch==1.33
      - langchain==1.2.7
      - langchain-core==1.2.7
      - langchain-google-genai==4.2.0
      - langchain-text-splitters==1.1.0
      - langgraph==1.0.7
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.7
      - langgraph-sdk==0.3.3
      - langsmith==0.6.6
      - multidict==6.7.1
      - multiprocess==0.70.16
      - opencv-python-headless==4.9.0.80
      - ormsgpack==1.12.2
      - packaging==25.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - pyarrow==23.0.0
      - pyarrow-hotfix==0.7
      - pywavelets==1.8.0
      - regex==2026.1.15
      - requests-toolbelt==1.0.0
      - safetensors==0.7.0
      - schedule==1.2.2
      - sentry-sdk==2.50.0
      - tenacity==9.1.2
      - tokenizers==0.19.1
      - transformers==4.40.1
      - uuid-utils==0.14.0
      - wandb==0.24.0
      - websockets==15.0.1
      - xxhash==3.6.0
      - zstandard==0.25.0
