name: ml_expressions
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=2.1.0=pyhd8ed1ab_1
  - alsa-lib=1.2.13=hb9d3cd8_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py39hf88036b_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.12.14=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.2=h3394656_1
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - contourpy=1.3.0=py39h74842e3_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.0=h59595ed_0
  - expat=2.6.4=h5888daf_0
  - flatbuffers=24.3.25=h59595ed_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py39h9399b63_1
  - freetype=2.12.1=h267a509_2
  - giflib=5.2.2=hd590300_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.13=h59595ed_1003
  - grpcio=1.65.5=py39hf8b6b1a_0
  - h2=4.1.0=pyhd8ed1ab_1
  - h5py=3.12.1=nompi_py39h394ba53_103
  - harfbuzz=10.1.0=h0b3b770_0
  - hdf5=1.14.4=nompi_h2d575fe_105
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=26_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=26_linux64_openblas
  - libclang-cpp19.1=19.1.6=default_hb5137d0_0
  - libclang13=19.1.6=default_h9c6a7e4_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgrpc=1.65.5=hf5c653b_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=26_linux64_openblas
  - libllvm19=19.1.6=ha7bfdaf_0
  - liblzma=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.2=h3b95a9b_1
  - libprotobuf=5.27.5=h5b01275_2
  - libre2-11=2024.07.02=hbbce691_2
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.13.5=h8d12d68_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=19.1.6=h024ca30_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - matplotlib=3.9.4=py39hf3d152e_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ml_dtypes=0.4.0=py39h3b40f6f_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - namex=0.0.8=pyhd8ed1ab_1
  - ncurses=6.5=he02047a_1
  - numpy=1.26.4=py39h474f0d3_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.4.0=h7b32b05_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optree=0.13.1=py39h74842e3_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h3b40f6f_1
  - pcre2=10.44=hba22ea6_2
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyside6=6.8.1=py39h0383914_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.21=h9c0c6dc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-flatbuffers=24.3.25=pyhe33e51e_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.9=5_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.1=h588cce1_2
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=13.9.4=pyhd8ed1ab_1
  - scikit-learn=1.6.0=py39h4b7350c_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - termcolor=2.5.0=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py39h8cd3c5a_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py39h8cd3c5a_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.0=py39h8cd3c5a_0
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py39h08a7858_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asttokens==3.0.0
      - cachetools==5.5.0
      - click==8.1.8
      - comm==0.2.2
      - debugpy==1.8.11
      - decorator==5.1.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastapi==0.115.6
      - ffmpy==0.5.0
      - filelock==3.16.1
      - fsspec==2024.12.0
      - gast==0.4.0
      - google-auth==2.37.0
      - google-auth-oauthlib==0.4.6
      - gradio==4.44.1
      - gradio-client==1.3.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - jinja2==3.1.5
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - keras==2.11.0
      - libclang==18.1.1
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - oauthlib==3.2.2
      - orjson==3.10.13
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.48
      - protobuf==3.19.6
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - ruff==0.8.6
      - safetensors==0.5.1
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.41.3
      - sympy==1.13.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tokenizers==0.21.0
      - tomlkit==0.12.0
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.47.1
      - triton==3.1.0
      - typer==0.15.1
      - uvicorn==0.34.0
      - wcwidth==0.2.13
      - websockets==12.0
      - widgetsnbextension==4.0.13
prefix: /opt/conda/envs/ml_expressions
