name: ml_expressions
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.1.0=pyhd8ed1ab_1
  - aiohappyeyeballs=2.4.4=pyhd8ed1ab_1
  - aiohttp=3.11.11=py39hd18e689_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - aom=3.7.1=h93d8f39_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py39h06d86d0_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_2
  - async-lru=2.0.4=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=24.3.0=pyh71513ae_0
  - aws-c-auth=0.7.3=hef4cc69_1
  - aws-c-cal=0.6.1=h03343b3_1
  - aws-c-common=0.9.0=h0dc2134_0
  - aws-c-compression=0.2.17=hc1c6d78_2
  - aws-c-event-stream=0.3.1=hf265e0f_4
  - aws-c-http=0.7.11=h4b92c67_4
  - aws-c-io=0.13.32=h9d499ee_1
  - aws-c-mqtt=0.9.3=hd869499_1
  - aws-c-s3=0.3.14=hbbd0165_1
  - aws-c-sdkutils=0.1.12=hc1c6d78_1
  - aws-checksums=0.1.17=hc1c6d78_1
  - aws-crt-cpp=0.21.0=hecd4c9a_5
  - aws-sdk-cpp=1.10.57=h3ff9d30_19
  - babel=2.16.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_1
  - bleach=6.2.0=pyhd8ed1ab_1
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.0.9=hb7f2c08_9
  - brotli-bin=1.0.9=hb7f2c08_9
  - brotli-python=1.0.9=py39h7a8716b_9
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.4=hf13058a_0
  - ca-certificates=2024.12.14=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_1
  - cairo=1.16.0=h09dd18c_1016
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py39h8ddeee6_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_1
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h0d3c867_2
  - cpython=3.9.21=py39hd8ed1ab_1
  - cryptography=44.0.0=py39hce2744d_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h0dc2134_0
  - debugpy=1.8.11=py39hdf37715_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - fastapi=0.103.2=pyhd8ed1ab_0
  - ffmpeg=6.1.0=gpl_h9a4e613_101
  - filelock=3.16.1=pyhd8ed1ab_1
  - flatbuffers=23.5.26=he965462_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py39hd18e689_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=h60636b9_2
  - fribidi=1.0.10=hbcb3906_0
  - frozenlist=1.5.0=py39h296a897_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.22.5=hdfe23c8_3
  - gettext-tools=0.22.5=hdfe23c8_3
  - gflags=2.2.2=hac325c4_1005
  - giflib=5.2.2=h10d778d_0
  - glog=0.6.0=h8ac2a54_0
  - gmp=6.3.0=hf036a51_2
  - gmpy2=2.1.5=py39h127c8af_3
  - gnutls=3.7.9=h1951705_0
  - google-auth=2.37.0=pyhd8ed1ab_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.13=h73e2aa4_1003
  - grpcio=1.54.3=py39h73e1029_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.1.0=pyhd8ed1ab_1
  - harfbuzz=7.3.0=h413ba03_0
  - hdf5=1.14.1=nompi_hedada53_100
  - hpack=4.0.0=pyhd8ed1ab_1
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.26.5=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=72.1=h7336db1_0
  - idna=3.10=pyhd8ed1ab_1
  - imageio=2.36.1=pyh12aca89_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib-resources=6.4.5=pyhd8ed1ab_1
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_1
  - ipykernel=6.29.5=py39hecd8cb5_0
  - ipython=8.18.1=pyh707e725_3
  - ipywidgets=8.1.5=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jasper=4.0.0=h794afb9_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py39h6e9494a_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.11.0=pyhd8ed1ab_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py39h0d8d0ca_0
  - krb5=1.21.3=h37d8d59_0
  - lame=3.100=hb7f2c08_1003
  - lcms2=2.15=h2dcdeff_1
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20230125.3=cxx17_h000cb23_0
  - libaec=1.1.3=h73e2aa4_0
  - libarrow=12.0.1=h64fc635_8_cpu
  - libasprintf=0.22.5=hdfe23c8_3
  - libasprintf-devel=0.22.5=hdfe23c8_3
  - libass=0.17.1=h66d2fa1_0
  - libblas=3.9.0=26_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_9
  - libbrotlidec=1.0.9=hb7f2c08_9
  - libbrotlienc=1.0.9=hb7f2c08_9
  - libcblas=3.9.0=26_osx64_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.11.1=h5dec5d8_0
  - libcxx=19.1.6=hf95d169_1
  - libdeflate=1.18=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.6.4=h240833e_0
  - libffi=3.4.2=h0d85af4_5
  - libgettextpo=0.22.5=hdfe23c8_3
  - libgettextpo-devel=0.22.5=hdfe23c8_3
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libglib=2.82.2=hb6ef654_0
  - libgoogle-cloud=2.12.0=h20eaa6e_1
  - libgrpc=1.54.3=hfaa49da_0
  - libhwloc=2.9.3=default_h24e0189_1009
  - libiconv=1.17=hd75f5a5_2
  - libidn2=2.3.7=h10d778d_0
  - libintl=0.22.5=hdfe23c8_3
  - libintl-devel=0.22.5=hdfe23c8_3
  - libjpeg-turbo=2.1.5.1=h0dc2134_1
  - liblapack=3.9.0=26_osx64_openblas
  - liblapacke=3.9.0=26_osx64_openblas
  - liblzma=5.6.3=hd471939_1
  - liblzma-devel=5.6.3=hd471939_1
  - libnghttp2=1.64.0=hc7306c3_0
  - libopenblas=0.3.28=openmp_hbf64a52_1
  - libopencv=4.7.0=py39h43b5454_6
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.44=h4b8f8c9_0
  - libprotobuf=3.21.12=h7d26f99_2
  - libsentencepiece=0.1.99=h5c8095a_1
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.47.2=hdb6dae5_0
  - libssh2=1.11.1=h3dc7d44_0
  - libtasn1=4.19.0=hb7f2c08_0
  - libthrift=0.18.1=h88b220a_2
  - libtiff=4.5.1=hf955e92_1
  - libunistring=0.9.10=h0d85af4_0
  - libutf8proc=2.8.0=he670073_1
  - libuv=1.44.2=h0dc2134_1
  - libvpx=1.13.1=he965462_0
  - libwebp-base=1.5.0=h6cf52b4_0
  - libxcb=1.15=hb7f2c08_0
  - libxml2=2.11.5=hd95e348_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=19.1.6=ha54dae1_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - markdown=3.6=pyhd8ed1ab_0
  - matplotlib=3.9.4=py39h6e9494a_0
  - matplotlib-base=3.9.4=py39hda06d36_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.0.2=pyhd8ed1ab_1
  - mkl=2022.2.1=h44ed08c_16952
  - mpc=1.3.1=h9d8efa1_1
  - mpfr=4.2.1=haed47dc_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.1.0=py39h781ac47_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhff2d567_2
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=hf036a51_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h8e11ae5_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nodejs=20.5.1=h46e3395_0
  - notebook=7.3.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py39h28c39a1_0
  - oauthlib=3.2.2=pyhd8ed1ab_1
  - opencv=4.7.0=py39h6e9494a_6
  - openh264=2.3.1=hf0c8a7f_2
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.4.0=hd471939_0
  - opt-einsum=3.4.0=hd8ed1ab_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - orc=1.9.0=hec59b76_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - p11-kit=0.24.1=h65f8906_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h88a5ddd_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h7634a1b_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.44.2=h1fd1274_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - propcache=0.2.1=py39h80efdc8_0
  - psutil=6.1.0=py39h296a897_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.7.0=py39h55f2206_6
  - pyarrow-hotfix=0.6=pyhd8ed1ab_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.1=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyobjc-core=10.3.2=py39h4881f39_0
  - pyobjc-framework-cocoa=10.3.2=py39h4881f39_0
  - pyopenssl=24.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.21=h7fafba3_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyhe33e51e_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python-xxhash=3.5.0=py39h06d86d0_1
  - python_abi=3.9=5_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.2=py39h06d86d0_1
  - pyzmq=26.2.0=py39h7644d4c_3
  - qhull=2020.2=h3c5361c_5
  - re2=2023.03.02=h096449b_0
  - readline=8.2=h9e318b2_1
  - referencing=0.35.1=pyhd8ed1ab_1
  - regex=2024.11.6=py39h80efdc8_0
  - requests=2.32.3=pyhd8ed1ab_1
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.22.3=py39hd8827cb_0
  - rsa=4.9=pyhd8ed1ab_1
  - safetensors=0.4.5=py39h6e5e23e_0
  - scipy=1.13.1=py39h038d4f4_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - sentencepiece=0.1.99=h6e9494a_1
  - sentencepiece-python=0.1.99=py39hefc2c85_1
  - sentencepiece-spm=0.1.99=h5c8095a_1
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.7=hfe0d17b_2
  - snappy=1.1.10=h6dc393e_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.27.0=pyhd8ed1ab_0
  - statsmodels=0.14.4=py39hff9a475_0
  - svt-av1=1.7.0=he965462_0
  - sympy=1.13.3=pyh2585a3b_104
  - tbb=2021.11.0=h7728843_1
  - tensorboard-data-server=0.7.0=py39hb2b0753_2
  - tensorflow-estimator=2.12.1=cpu_py39h8a426f1_0
  - termcolor=2.5.0=pyhd8ed1ab_1
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - tokenizers=0.21.0=py39hde49db8_0
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py39h80efdc8_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - transformers=4.47.1=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py39h296a897_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uvicorn=0.34.0=pyh31011fe_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.13=pyhd8ed1ab_1
  - wrapt=1.17.0=py39h80efdc8_0
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xxhash=0.8.2=h4140336_0
  - xz=5.6.3=h357f2ed_1
  - xz-gpl-tools=5.6.3=h357f2ed_1
  - xz-tools=5.6.3=hd471939_1
  - yaml=0.2.5=h0d85af4_2
  - yarl=1.18.3=py39h80efdc8_0
  - zeromq=4.3.5=h7130eaa_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hd23fc13_2
  - zstandard=0.23.0=py39hc23f734_1
  - zstd=1.5.6=h915ae27_0
  - pip:
      - accelerate==0.34.2
      - adagio==0.2.6
      - aiofiles==23.2.1
      - aiohttp-cors==0.7.0
      - alembic==1.14.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - autogluon==1.2
      - autogluon-common==1.2
      - autogluon-core==1.2
      - autogluon-features==1.2
      - autogluon-multimodal==1.2
      - autogluon-tabular==1.2
      - autogluon-timeseries==1.2
      - blis==0.7.11
      - boto3==1.35.87
      - botocore==1.35.87
      - catalogue==2.0.10
      - catboost==1.2.7
      - cloudpathlib==0.20.0
      - cloudpickle==3.1.0
      - colorful==0.5.6
      - colorlog==6.9.0
      - confection==0.1.5
      - coreforecast==0.0.12
      - cymem==2.0.10
      - datasets==3.2.0
      - distlib==0.3.9
      - einops==0.8.0
      - evaluate==0.4.3
      - facenet-pytorch==2.6.0
      - fastai==2.7.18
      - fastcore==1.7.27
      - fastdownload==0.0.7
      - fastprogress==1.0.3
      - ffmpy==0.5.0
      - fs==2.4.16
      - fugue==0.9.1
      - future==1.0.0
      - gdown==5.2.0
      - gluonts==0.16.0
      - google-api-core==2.24.0
      - googleapis-common-protos==1.66.0
      - gradio==4.20.0
      - gradio-client==0.11.0
      - greenlet==3.1.1
      - h5py==3.12.1
      - hyperopt==0.2.7
      - jax==0.4.13
      - jaxlib==0.4.13
      - jmespath==1.0.1
      - jsonschema==4.21.1
      - kagglehub==0.3.5
      - keras==3.7.0
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightgbm==4.5.0
      - lightning==2.5.0.post0
      - lightning-utilities==0.11.9
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - mako==1.3.8
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.15.0
      - ml-dtypes==0.3.1
      - mlforecast==0.13.4
      - model-index==0.1.11
      - msgpack==1.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.11
      - namex==0.0.8
      - narwhals==1.19.1
      - nlpaug==1.1.11
      - nltk==3.8.1
      - numba==0.60.0
      - nvidia-ml-py3==7.352.0
      - omegaconf==2.2.3
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-contrib-python==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.11
      - optree==0.13.1
      - optuna==4.1.0
      - ordered-set==4.1.0
      - orjson==3.10.12
      - pdf2image==1.17.0
      - pillow==10.2.0
      - plotly==5.24.1
      - preshed==3.0.9
      - proto-plus==1.25.0
      - protobuf==3.20.3
      - py-spy==0.4.0
      - py4j==0.10.9.8
      - pyarrow==17.0.0
      - pycryptodome==3.21.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pytesseract==0.3.10
      - python-graphviz==0.20.3
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.0.post0
      - pytorch-metric-learning==2.3.0
      - ray==2.39.0
      - rich==13.9.4
      - ruff==0.8.4
      - s3transfer==0.10.4
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - semantic-version==2.10.0
      - seqeval==1.2.2
      - shellingham==1.5.4
      - smart-open==7.1.0
      - sounddevice==0.5.1
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.36
      - srsly==2.5.0
      - statsforecast==1.7.8
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.16.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.16.2
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - text-unidecode==1.3
      - textual==1.0.0
      - tf-keras==2.16.0
      - thinc==8.2.5
      - tifffile==2024.8.30
      - timm==1.0.3
      - tomlkit==0.12.0
      - toolz==0.12.1
      - torch==2.2.2
      - torchmetrics==1.2.1
      - torchvision==0.17.2
      - triad==0.9.8
      - typer==0.15.1
      - typing-extensions==4.12.2
      - uc-micro-py==1.0.3
      - urllib3==1.26.20
      - utilsforecast==0.2.4
      - virtualenv==20.28.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - websockets==11.0.3
      - window-ops==0.0.15
      - xgboost==2.1.3
prefix: /opt/anaconda3/envs/ml_expressions
