name: ml_expressions
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - absl-py=2.1.0=pyhd8ed1ab_1
  - alsa-lib=1.2.13=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - astunparse=1.6.3=pyhd8ed1ab_3
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py39hf88036b_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2024.12.14=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.2=h3394656_1
  - certifi=2024.12.14=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - contourpy=1.3.0=py39h74842e3_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.0=h59595ed_0
  - expat=2.6.4=h5888daf_0
  - ffmpeg=7.1.0=gpl_h099772d_709
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.1.0=pyhd8ed1ab_1
  - h5py=3.12.1=nompi_py39h394ba53_103
  - harfbuzz=10.1.0=h0b3b770_0
  - hdf5=1.14.4=nompi_h2d575fe_105
  - hpack=4.0.0=pyhd8ed1ab_1
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imath=3.1.12=h7955e40_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jasper=4.2.4=h536e39c_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - level-zero=1.19.2=h84d6215_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libass=0.17.3=hba53ac1_1
  - libblas=3.9.0=26_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=26_linux64_openblas
  - libclang-cpp19.1=19.1.6=default_hb5137d0_0
  - libclang13=19.1.6=default_h9c6a7e4_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.11.1=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.82.2=h2ff4ddf_0
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgrpc=1.67.1=h25350d4_1
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=26_linux64_openblas
  - liblapacke=3.9.0=26_linux64_openblas
  - libllvm19=19.1.6=ha7bfdaf_0
  - liblzma=5.6.3=hb9d3cd8_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libopencv=4.10.0=qt6_py39hf5bbdc2_615
  - libopengl=1.7.0=ha4b6fd6_2
  - libopenvino=2024.6.0=hac27bb2_3
  - libopenvino-auto-batch-plugin=2024.6.0=h4d9b6c2_3
  - libopenvino-auto-plugin=2024.6.0=h4d9b6c2_3
  - libopenvino-hetero-plugin=2024.6.0=h3f63f65_3
  - libopenvino-intel-cpu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-intel-gpu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-intel-npu-plugin=2024.6.0=hac27bb2_3
  - libopenvino-ir-frontend=2024.6.0=h3f63f65_3
  - libopenvino-onnx-frontend=2024.6.0=h6363af5_3
  - libopenvino-paddle-frontend=2024.6.0=h6363af5_3
  - libopenvino-pytorch-frontend=2024.6.0=h5888daf_3
  - libopenvino-tensorflow-frontend=2024.6.0=h630ec5c_3
  - libopenvino-tensorflow-lite-frontend=2024.6.0=h5888daf_3
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=17.2=h3b95a9b_1
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - librsvg=2.58.4=h49af25d_2
  - libsqlite=3.47.2=hee588c1_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libva=2.22.0=h8a09558_1
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.13.5=h8d12d68_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=19.1.6=h024ca30_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - namex=0.0.8=pyhd8ed1ab_1
  - ncurses=6.5=he02047a_1
  - nodejs=22.12.0=hf235a45_0
  - ocl-icd=2.3.2=hb9d3cd8_2
  - opencl-headers=2024.10.24=h5888daf_0
  - opencv=4.10.0=qt6_py39he2731b8_615
  - openexr=3.3.2=h6326327_1
  - openh264=2.5.0=hf92e6e3_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.4.0=h7b32b05_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h3b40f6f_1
  - pango=1.54.0=h861ebed_4
  - pcre2=10.44=hba22ea6_2
  - pip=24.3.1=pyh8b19718_2
  - pixman=0.44.2=h29eaf8c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.14=h59595ed_0
  - py-opencv=4.10.0=qt6_py39he979a1a_615
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyside6=6.8.1=py39h0383914_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.21=h9c0c6dc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.9=5_cp39
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.1=h588cce1_2
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_1
  - scikit-learn=1.6.0=py39h4b7350c_0
  - scipy=1.13.1=py39haf93ffa_0
  - snappy=1.2.1=h8bd8927_1
  - svt-av1=2.3.0=h5888daf_0
  - tbb=2022.0.0=hceb3a55_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.2=py39h8cd3c5a_0
  - tzdata=2024b=hc8b5060_0
  - unicodedata2=15.1.0=py39h8cd3c5a_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.10=h4f16b4b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39h08a7858_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==24.3.0
      - av==12.3.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==5.5.0
      - click==8.1.8
      - comm==0.2.2
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dnspython==2.7.0
      - easyprocess==1.1
      - entrypoint2==1.1
      - entrypoints==0.4
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - facenet-pytorch==2.6.0
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.16.1
      - flatbuffers==2.0
      - fonttools==4.55.4
      - fqdn==1.5.1
      - fsspec==2024.12.0
      - gast==0.4.0
      - google-auth==2.37.0
      - google-auth-oauthlib==0.4.6
      - google-crc32c==1.6.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - grpcio==1.69.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - ifaddr==0.2.0
      - importlib-metadata==8.6.1
      - inflate64==1.0.1
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==2.11.0
      - keras-nightly==2.5.0.dev2021032900
      - libclang==18.1.1
      - markdown==3.7
      - markupsafe==2.1.3
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.7
      - mistune==3.1.0
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - multivolumefile==0.2.3
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opt-einsum==3.4.0
      - optree==0.14.0
      - orjson==3.10.13
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - patool==1.15.0
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - protobuf==3.19.6
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py7zr==0.22.0
      - pyarrow==19.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybcj==1.0.3
      - pycryptodomex==3.21.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pydub==0.25.1
      - pyee==12.1.1
      - pylibsrtp==0.10.0
      - pympler==1.1
      - pyppmd==1.1.1
      - python-json-logger==3.2.1
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyunpack==0.3
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - pyzstd==0.16.2
      - referencing==0.36.0
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - ruff==0.8.6
      - safetensors==0.5.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - semver==3.0.2
      - send2trash==1.8.3
      - setuptools==75.8.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.41.3
      - sympy==1.13.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - texttable==1.7.0
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.12.0
      - toolz==1.0.0
      - torch==2.2.0+cu118
      - torchvision==0.17.0+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.47.1
      - triton==2.2.0
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzlocal==5.2
      - uri-template==1.3.0
      - uvicorn==0.34.0
      - validators==0.34.0
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
prefix: /opt/conda/envs/ml_expressions
