name: ml_expressions_face
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.12.14=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.3=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.48.0=hee588c1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_2
  - openssl=3.4.0=h7b32b05_1
  - pip=24.3.1=pyh8b19718_2
  - python=3.9.21=h9c0c6dc_1_cpython
  - readline=8.2=h8228510_1
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.1.0
      - aioice==0.9.0
      - aiortc==1.9.0
      - altair==4.2.2
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==25.1.0
      - av==12.3.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==5.5.1
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cmake==3.25.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cryptography==44.0.0
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dlib==19.24.6
      - dnspython==2.7.0
      - entrypoints==0.4
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - facenet-pytorch==2.6.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - flatbuffers==25.1.24
      - fonttools==4.55.4
      - fqdn==1.5.1
      - fsspec==2024.2.0
      - gast==0.4.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==0.4.6
      - google-crc32c==1.6.0
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ifaddr==0.2.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jinja2==3.1.5
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==2.11.0
      - keras-nightly==2.5.0.dev2021032900
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - lit==15.0.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.0
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - namex==0.0.8
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==2.0.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.6.0.66
      - opt-einsum==3.3.0
      - optree==0.14.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.4.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==3.19.6
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydeck==0.9.1
      - pyee==12.1.1
      - pygments==2.19.1
      - pylibsrtp==0.10.0
      - pympler==1.1
      - pyopenssl==24.3.0
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.36.0
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retina-face==0.0.17
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.0
      - rpds-py==0.22.3
      - rsa==4.9
      - scipy==1.10.1
      - seaborn==0.13.2
      - semver==3.0.4
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - setuptools==75.8.0
      - six==1.15.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - streamlit==1.10.0
      - streamlit-webrtc==0.42.0
      - sympy==1.13.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==1.1.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==2.2.2
      - torchvision==0.17.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==2.2.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - tzlocal==5.2
      - ultralytics==8.3.67
      - ultralytics-thop==2.0.14
      - uri-template==1.3.0
      - urllib3==2.3.0
      - validators==0.34.0
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.12.1
      - zipp==3.21.0
prefix: /opt/conda/envs/ml_expressions_face
