# speech: SpeechRecognition, pydub, or librosa 
# my even integrate TensorFlow Audio 
name: ml_extorch
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Core Libraries
  - python=3.10
  - numpy=1.26.0
  - pandas=2.1.2
  - matplotlib=3.8.0
  - pillow=10.0.0
  - scikit-learn=1.3.2
  - seaborn=0.12.2
  - jupyter=1.0.0

  # PyTorch Ecosystem
  - pytorch=2.0.0
  - torchvision=0.15.1

  # Pip and Additional Packages
  - pip
  - pip:
      - plotly==5.15.0
      - gradio==4.44.1
      - autogluon==1.2
      - autogluon-multimodal==1.2