name: ml_extensor
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - anyio=4.7.0
  - aom=3.5.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2024.12.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - cairo=1.16.0
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cryptography=44.0.0
  - cycler=0.12.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ffmpeg=5.1.2
  - flatbuffers=23.3.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.5.0
  - gast=0.4.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gmp=6.3.0
  - gnutls=3.7.9
  - google-auth=2.37.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.51.1
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.9.0
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.10
  - imageio=2.36.1
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jasper=4.0.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.11.1
  - libcxx=19.1.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libgrpc=1.51.1
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libopencv=4.7.0
  - libopus=1.3.1
  - libpng=1.6.44
  - libprotobuf=3.21.12
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libssh2=1.11.1
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libwebp-base=1.5.0
  - libxcb=1.15
  - libxml2=2.10.3
  - libzlib=1.3.1
  - llvm-openmp=19.1.6
  - markdown=3.6
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - multidict=6.1.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - oauthlib=3.2.2
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.4.0
  - opt_einsum=3.4.0
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - propcache=0.2.1
  - protobuf=4.21.12
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-opencv=4.7.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pygments=2.18.0
  - pyjwt=2.10.1
  - pyobjc-core=10.3.2
  - pyobjc-framework-cocoa=10.3.2
  - pyopenssl=24.3.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - re2=2023.02.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - rsa=4.9
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.6.0
  - six=1.17.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=1.4.1
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - termcolor=2.5.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiofiles==23.2.1
      - altair==5.5.0
      - annotated-types==0.7.0
      - autogluon-common==1.2
      - autogluon-core==1.2
      - autogluon-features==1.2
      - autogluon-tabular==1.2
      - boto3==1.35.86
      - botocore==1.35.86
      - fastapi==0.115.6
      - ffmpy==0.5.0
      - filelock==3.16.1
      - fsspec==2024.12.0
      - gradio==4.20.0
      - gradio-client==0.11.0
      - huggingface-hub==0.27.0
      - jmespath==1.0.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - narwhals==1.19.1
      - networkx==3.2.1
      - orjson==3.10.12
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - python-multipart==0.0.20
      - rich==13.9.4
      - ruff==0.8.4
      - s3transfer==0.10.4
      - scikit-learn==1.5.2
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - starlette==0.41.3
      - tomlkit==0.12.0
      - typer==0.15.1
      - urllib3==1.26.20
      - uvicorn==0.34.0
      - websockets==11.0.3
prefix: /opt/anaconda3/envs/ml_extensor
